### PR TITLE
增加IP代理认证功能

### PR DESCRIPTION
**Pull request by oxf1**
以前的代理功能不能提供认证。但是从网上买来的代理一般都是有用户和密码认证的。
用法：
```java
        site.setHttpProxyPool(Lists.newArrayList(
                new String[]{"userA", "pswA", "103.27.125.250", "8000"},
                new String[]{"userB", "pswB", "103.24.125.251", "8000"}
        ), false);


```

### CODE REVIEW

**Comment by robin-obrien** [comment]
@oxf1 
How can I use this commit in my code, it is exactly what I need!

**Comment by oxf1** [comment]
@robin-obrien  the author of webmagic has not accept my patch. You can refer to  my commit https://github.com/code4craft/webmagic/pull/196/commits/9ff0ca2dc79039258a3968381f9b57102e3d3a88

**Comment by robin-obrien** [comment]
@oxf1, I downloaded the code and merged it manually, well done. It works very well. Thanks!
@code4craft, you should consider adding this commit, excellent work

**Comment by code4craft** [comment]
Merged on [https://github.com/code4craft/webmagic/commit/83c27ebbc4090040f4a98b3f5b2c7a86ca33a152](https://github.com/code4craft/webmagic/commit/83c27ebbc4090040f4a98b3f5b2c7a86ca33a152)

Thanks for your contribution!

**Pull request closed without merging**
